services:
  - type: web
    name: agrovest-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: sb_secret_JI7_6GPh-cGMC5xtVd3iPg_489nhmhU
        generateValue: true
      - key: https://igtfcidpbfwnegolcadb.supabase.co
        sync: false          # You paste this from Supabase manually
      - key: RENDER_TMP
        value: "true"
      - key: PYTHON_VERSION
        value: "3.14"
